### ISSUE TITLE
「のみ」がないと検索できない

### ISSUE THREAD

**Issue by ndac-todoroki** [ndac-todoroki/DiscordSplatoonBot#15]
「ブキランダム　ローラー」でローラーのみの検索がなされてほしい

### 現在のエラー

```elixir
[debug] %Nostrum.Struct.Message{activity: nil, application: nil, attachments: [], author: %Nostrum.Struct.User{avatar: "3bb5c6a599162ca1e2e0d724b6b88912", bot: nil, discriminator: "3299", email: nil, id: 229167078110789633, mfa_enabled: nil, username: "ndac_todoroki", verified: nil}, channel_id: 260291356562423809, content: "ブキランダム ローラー", edited_timestamp: nil, embeds: [], guild_id: 260291356562423809, id: 547038204948250637, member: %Nostrum.Struct.Guild.Member{deaf: false, joined_at: "2016-12-19T06:24:55.396000+00:00", mute: false, nick: nil, roles: [340708769438760965, 340711744496336897], user: nil}, mention_everyone: false, mention_roles: [], mentions: [], nonce: 553208983326818304, pinned: false, reactions: nil, timestamp: "2019-02-18T12:54:31.538000+00:00", tts: false, type: 0, webhook_id: nil}
["ローラー"]
[error] Task #PID<0.20525.0> started from #PID<0.859.0> terminating
** (RuntimeError) tmp_listに余りがあります。コマンドミスの可能性が高いです
    (splatoon_data) lib/splatoon_data/weapons/weapons.ex:143: SplatoonData.Weapons.parse_opts/3
    (splatoon_data) lib/splatoon_data/weapons/weapons.ex:95: SplatoonData.Weapons.list_weapons/1
    (discord_splatoon_bot) lib/discord_splatoon_bot/command/splatoon.ex:91: DiscordSplatoonBot.Command.Splatoon.list_weapons/1
    (discord_splatoon_bot) lib/discord_splatoon_bot/command/splatoon.ex:10: DiscordSplatoonBot.Command.Splatoon.random_weapons/2
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Function: #Function<0.109182554/0 in DiscordSplatoonBot.Consumer.start_link/1>
    Args: []
```

**Comment by ndac-todoroki** [comment]
「のみ」「以外」が一つもなかった場合に「のみ」として扱うことにする？
